---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/component: controller
    app.kubernetes.io/name: kueue
    control-plane: controller-manager
    rbac.kueue.x-k8s.io/batch-admin: 'true'
  name: kueue-pending-workloads-cq-viewer-role
rules:
- apiGroups:
  - visibility.kueue.x-k8s.io
  resources:
  - clusterqueues/pendingworkloads
  verbs:
  - get
  - list
  - watch
