kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: kueue-manager-rolebinding
subjects:
  - kind: ServiceAccount
    name: kueue-controller-manager
    namespace: kueue-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kueue-manager-role