apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/component: controller
    app.kubernetes.io/name: kueue
    control-plane: controller-manager
  name: kueue-visibility-server
  namespace: openshift-kueue-operator
spec:
  ports:
    - name: https
      port: 443
      protocol: TCP
      targetPort: 8082
  selector:
    control-plane: controller-manager