name: Sync Kueue Manifests

on:
  schedule:
    - cron: '0 0 * * *'  # Run daily at midnight UTC
  workflow_dispatch:      # Allow manual triggering

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          repository: sohankunkerkar/kueue-operator
          path: kueue-operator

      - name: Debug working directory
        run: |
          echo "Current directory: $(pwd)"
          ls -R

      - name: List contents of hack directory
        run: |
          ls -R ./kueue-operator/hack

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyyaml requests

      - name: Run sync script
        run: |
          python hack/sync_manifests.py
        working-directory: ./kueue-operator

      - name: Check for changes
        id: changes
        run: |
          git add .
          if git diff --cached --quiet; then
            echo "No changes detected."
            echo "changes_detected=false" >> $GITHUB_OUTPUT
          else
            echo "Changes detected."
            echo "changes_detected=true" >> $GITHUB_OUTPUT
          fi
        working-directory: ./kueue-operator

      - name: Create new branch and push changes
        if: steps.changes.outputs.changes_detected == 'true'
        run: |
          git config --global user.name "Your GitHub Username"
          git config --global user.email "your-email@example.com"
          git checkout -b sync-kueue-manifests
          git commit -m "Sync Kueue manifests for version $(python -c 'import os; print(os.path.basename(os.getcwd()))')"
          git push origin sync-kueue-manifests
        working-directory: ./kueue-operator

      - name: Create Pull Request
        if: steps.changes.outputs.changes_detected == 'true'
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          title: "Sync Kueue manifests for version $(python -c 'import os; print(os.path.basename(os.getcwd()))')"
          body: "Automated PR to sync Kueue manifests."
          branch: "sync-kueue-manifests"
          base: main
          draft: false
